name: Build and Deploy site to Nekoweb

on:
  push:
    branches: [ "main" ]

permissions: 
  contents: write

jobs:
    build:
        runs-on: ubuntu-latest
        strategy:
          matrix:
            python-version: [ "3.12" ]
        steps:
            - uses: actions/checkout@v4
            - name: Set up Python ${{ matrix.python-version }}
              uses: actions/setup-python@v4
              with:
                python-version: ${{ matrix.python-version }}
            - name: Install Python dependencies
              uses: py-actions/py-dependency-install@v4
              with:
                path: "requirements.txt"
            - name: Pull Changes
              run: |
                git pull
            - name: Build Site
              run: python main.py
            - name: Deploy to Nekoweb
              uses: mp-pinheiro/nekoweb-deploy@main
              with:
                API_KEY: ${{ secrets.NEKOWEB_API_KEY }}
                BUILD_DIR: "./build"
                DEPLOY_DIR: "/"
                CLEANUP: "False"
                DELAY: "0.5"
                NEKOWEB_PAGENAME: "wiki"
    deploy:
      if: "contains(github.event.head_commit.message, '#action/build-deploy')"
      needs: [build]
      runs-on: ubuntu-latest
      strategy:
        matrix:
          python-version: [ "3.12" ]
      steps:
        - name: Deploy to Nekoweb
          uses: mp-pinheiro/nekoweb-deploy@main
          with:
            API_KEY: ${{ secrets.NEKOWEB_API_KEY }}
            BUILD_DIR: "./build"
            DEPLOY_DIR: "/"
            CLEANUP: "False"
            DELAY: "0.5"
            NEKOWEB_PAGENAME: "wiki"
